#!/usr/bin/env python

#
#  Copyright 2009, Aryaka Networks. All rights reserved.
# 

#
# This file contains definitions for DOS error codes. For more details please 
# refer to SMB specs (either leach and/or SNIA).
#

# DOS Error classes
ERRDOS = 0x01   # Error is from the core DOS operating system set.
ERRSRV = 0x02   # Error is generated by the server network file manager.
ERRHRD = 0x03   # Error is an hardware error.
ERRCMD = 0xFF   # Command was not in the "SMB" format.

# Error codes for the ERRDOS error class
ERRsuccess           = 0    # Request was successful
ERRbadfunc           = 1    # Invalid function
ERRbadfile           = 2    # File not found (last component not found) 
ERRbadpath           = 3    # Directory not found (directory component not found)
ERRnofids            = 4    # Too many open files 
ERRnoaccess          = 5    # Access denied 
ERRbadfid            = 6    # Invalid file handle (fid) 
ERRbadmcb            = 7    # Memory control blocks destroyed.
ERRnomem             = 8    # Insufficient server memory to perform requested op.
ERRbadmem            = 9    # Invalid memory block address 
ERRbadenv            = 10   # Invalid environment 
ERRbadformat         = 11   # Invalid Format 
ERRbadaccess         = 12   # Invalid open mode 
ERRbaddata           = 13   # Invalid data (generally only by IOCTL calls 
                                            # within server) 
ERRres               = 14   # reserved 
ERRbaddrive          = 15   # Invalid drive 
ERRremcd             = 16   # Attempt to delete current directory 
ERRdiffdevice        = 17   # Not same device (e.g. cross volume rename was 
                                            # attempted)
ERRnofiles           = 18   # A File Search command can find no more files
                                            # matching the specified criteria.
ERRgeneral           = 31   # General failure 
ERRbadshare          = 32   # The Share mode on specified for an open
                                            # file conflict with open mode 
ERRlock              = 33   # Lock request conflicts with existing lock 
ERRunsup             = 50   # unsupported op
ERRnetnamedel        = 64   # Network name deleted or not available 
ERRnosuchshare       = 67   # Share name specified in the request is invalid.
ERRfilexists         = 80   # The File named in the request already exists.
ERRinvalidparam      = 87
ERRcannotopen        = 110  # Cannot open the file specified 
ERRbufferoverflow    = 111
ERRinsufficientbuffer= 122
ERRinvalidname       = 123  # Invalid name 
ERRunknownlevel      = 124
ERRnotlocked         = 158  # This region is not locked by this locking context. 
ERRinvalidpath       = 161
ERRcancelviolation   = 173
ERRnoatomiclocks     = 174
ERRrename            = 183
ERRbadpipe           = 230  # Named pipe invalid 
ERRpipebusy          = 231  # All instances of pipe are busy 
ERRpipeclosing       = 232  # named pipe close in progress 
ERRnotconnected      = 233  # No process on other end of named pipe 
ERRmoredata          = 234  # More data to be returned 
ERReainconsistent    = 255
ERRnomoreitems       = 259
ERRbaddirectory      = 267  # Invalid directory name in a path. 
ERReasnotsupported   = 282  # Extended attributes 
ERRquota             = 512  # The operation would cause a quota limit to be
                                            # exceeded.
ERRnotalink          = 513  # A link operation was performed on a pathname that
                                            # was not a link
ERRlogonfailure      = 1326 # Unknown username or bad password 
ERRbuftoosmall       = 2123
ERRunknownipc        = 2142
ERRnosuchprintjob    = 2151
ERRinvgroup          = 2455

# Error codes for the ERRSRV class 

ERRerror             = 1    # Non-specific error code 
ERRbadpw             = 2    # Bad password 
ERRbadtype           = 3    # reserved 
ERRaccess            = 4    # Access denied
ERRinvnid            = 5    # The TID specified in a command was invalid 
ERRinvnetname        = 6    # Invalid network name in tree connect
ERRinvdevice         = 7    # Invalid device 
ERRqfull             = 49   # Print queue full - returned by open print file
ERRqtoobig           = 50   # Print queue full -- no space
ERRinvpfid           = 52   # Invalid print file FID
ERRsmbcmd            = 64   # Server did not recognize the command received
ERRsrverror          = 65   # Server internal error 
ERRfilespecs         = 67   # fid and pathname invalid combination 
ERRbadlink           = 68   # reserved 
ERRbadpermits        = 69   # Access specified for a file is not a valid 
                                            # combination.
ERRbadpid            = 70
ERRsetattrmode       = 71   # The attribute mode in Set File attribute is invalid 
ERRpaused            = 81   # Message server paused 
ERRmsgoff            = 82   # Not receiving messages 
ERRnoroom            = 83   # No room to buffer message 
ERRrmuns             = 87   # too many remote usernames 
ERRtimeout           = 88   # operation timed out 
ERRnoresource        = 89   # No resources currently available for request. 
ERRtoomanyuids       = 90   # Too many UIDs active on this session.
ERRbaduid            = 91   # The UID is not known as a valid user identifier 
                                            # on this session.
ERRuseMPX            = 250  # temporarily unable to use raw mode, use MPX mode 
ERRuseSTD            = 251  # temporarily unable to use raw mode, 
                                            # use standard read/write 
ERRcontMPX           = 252  # Continue in MPX mode 
ERRnosupport         = 0xFFFF# Function not supported

# Error codes for the ERRHRD class 
ERRnowrite           = 19   # Attempt to write on write-protected media
ERRbadunit           = 20   # Unknown unit 
ERRnotready          = 21   # Drive not ready 
ERRbadcmd            = 22   # Unknown command 
ERRdata              = 23   # Data error (CRC)
ERRbadreq            = 24   # Bad request structure length 
ERRseek              = 25   # Seek error
ERRbadmedia          = 26   # Unknown media type
ERRbadsector         = 27   # Sector not found
ERRnopaper           = 28   # Priter out of paper
ERRwrite             = 29   # write fault 
ERRread              = 30   # read fault 
ERRwrongdisk         = 34   # The wrond disk was found in a drive
ERRFCBunavail        = 35   # No FCBs are available to process request.
ERRsharebufexc       = 36   # share buffer exceeded 
ERRdiskfull          = 39


